backend:
  name: git-gateway
  branch: main  # zmeň podľa vetvy v GitHube

  publish_mode: editorial_workflow  # TOTO PRIDAJTE

media_folder: "Images"       # kde sa ukladajú obrázky v repozitári
public_folder: "/Images"     # cesta z pohľadu webu

collections:
  - name: "global"
    label: "Globálny obsah"
    folder: "Global"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }

  - name: "podlahy"
    label: "Podlahy"
    folder: "Podlahy"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Názov", name: "title", widget: "string" }
      - { label: "Popis", name: "body", widget: "markdown" }

  - name: "realizacie"
    label: "Realizácie"
    folder: "Realizacie"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Názov projektu", name: "title", widget: "string" }
      - { label: "Popis", name: "description", widget: "markdown" }
      - { label: "Obrázok", name: "image", widget: "image" }
